cc_test(
    name = "noop_test",
    srcs = [
        "noop_test.cc",
    ],
    deps = [
        "//api",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "span_id_test",
    srcs = [
        "span_id_test.cc",
    ],
    deps = [
        "//api",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
      name = "global_provider",
      srcs = [
          "global_provider_test.cc",
      ],
    deps = [
        "//api",
        "@com_google_googletest//:gtest_main",
    ],
)
